apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-171065189
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-171065189
    app.kubernetes.io/part-of: test-app-171065189
  name: go-171065189
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: go-171065189
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: go-171065189
    spec:
      containers:
      - env:
        - name: TEST_ENV_VAR
          value: Test go app
        image: quay.io/hacdev/qxnjg3yh-tenant/test-app-171065189/go-171065189@sha256:09964d1ee3627fec2cecae3b37fcbd2975e3cc5aa865f5784ff9f20255816ca5
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
